#!/usr/bin/env php
<?php
define("LARAVEL_START", microtime(true));

// Load Composer's autoloader
require __DIR__ . "/vendor/autoload.php";

$app = require_once __DIR__ . "/bootstrap/app.php";

// Execute the Artisan console application
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput(),
    new Symfony\Component\Console\Output\ConsoleOutput()
);

// Terminate the application
$kernel->terminate($input, $status);

exit($status);

