<?php
namespace App\Http\Controllers\Chat;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use OpenAI;
use App\Repositories\DynamicProfileAttributesRepository;
use Illuminate\Support\Facades\Validator;

/**
 * Handles chatbot interactions with OpenAI integration.
 */
class ChatController extends Controller
{
    protected DynamicProfileAttributesRepository $attributesRepository;

    /**
     * Inject the repository for dynamic profile attributes.
     */
    public function __construct(DynamicProfileAttributesRepository $attributesRepository)
    {
        $this->attributesRepository = $attributesRepository;
    }

    /**
     * Process user messages and generate chatbot responses.
     *
     * Accepts an array of messages and returns a response generated by OpenAI's GPT-4 model.
     * Manages user profile attributes dynamically based on the conversation.
     *
     * @group Chat
     * @authenticated
     *
     * @bodyParam messages array required An array of message objects with 'role' and 'content'.
     *
     * @response 200 {
     *   "message": "Chatbot response generated successfully.",
     *   "data": {
     *     "response": "For optimal muscle growth, training each muscle group twice a week is recommended.",
     *     "updated_attributes": {
     *       "preferred_training_frequency": "twice a week"
     *     },
     *     "deleted_attributes": []
     *   }
     * }
     *
     * @response 422 {
     *   "message": "Validation failed.",
     *   "errors": {
     *     "messages": ["The messages field is required."]
     *   }
     * }
     *
     * @response 500 {
     *   "message": "An error occurred while generating the response.",
     *   "error": "Internal server error."
     * }
     */
    public function interact(Request $request)
    {
        $user = $request->user();

        // Validate the request input
        $validator = Validator::make($request->all(), [
            'messages' => 'required|array',
            'messages.*.role' => 'required|string|in:user,assistant',
            'messages.*.content' => 'required|string',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'message' => 'Validation failed.',
                'errors' => $validator->errors(),
            ], 422);
        }

        // Retrieve user attributes to include in the context
        $userAttributes = $this->attributesRepository->getAttributesForUser($user->id)->toArray();

        // Prepare the system prompt with user attributes
        $systemPrompt = "User profile attributes: " . json_encode($userAttributes);

        // Prepend the system prompt to the messages
        $messages = array_merge([
            ['role' => 'system', 'content' => $systemPrompt],
        ], $request->messages);

        // Initialize the OpenAI client
        $openAiApiKey = config('services.openai.api_key');
        $client = OpenAI::client($openAiApiKey);

        // Initialize arrays to keep track of attribute changes
        $updatedAttributes = [];
        $deletedAttributes = [];

        try {
            // Call the OpenAI API with function definitions for attribute management
            $response = $client->chat()->create([
                'model' => 'gpt-4',
                'messages' => $messages,
                'functions' => [
                    [
                        'name' => 'manage_attributes',
                        'description' => 'Manage multiple attributes for the user profile',
                        'parameters' => [
                            'type' => 'object',
                            'properties' => [
                                'operations' => [
                                    'type' => 'array',
                                    'items' => [
                                        'type' => 'object',
                                        'properties' => [
                                            'action' => [
                                                'type' => 'string',
                                                'enum' => ['add', 'update', 'delete'],
                                                'description' => 'The action to perform on the attribute',
                                            ],
                                            'key' => [
                                                'type' => 'string',
                                                'description' => 'The attribute key',
                                            ],
                                            'value' => [
                                                'type' => 'string',
                                                'description' => 'The attribute value (required for add or update actions)',
                                            ],
                                        ],
                                        'required' => ['action', 'key'],
                                    ],
                                ],
                            ],
                            'required' => ['operations'],
                        ],
                    ],
                ],
                'function_call' => 'auto',
            ]);

            $chatMessage = $response->choices[0]->message;

            // Handle function calls if any
            if (isset($chatMessage->functionCall)) {
                $functionName = $chatMessage->functionCall->name;
                $arguments = json_decode($chatMessage->functionCall->arguments, true);

                if ($functionName === 'manage_attributes') {
                    $operations = $arguments['operations'] ?? [];
                    foreach ($operations as $operation) {
                        $action = $operation['action'];
                        $key = $operation['key'];
                        $value = $operation['value'] ?? null;

                        switch ($action) {
                            case 'add':
                            case 'update':
                                $this->attributesRepository->setAttributeForUser($user->id, $key, $value);
                                $updatedAttributes[$key] = $value;
                                break;
                            case 'delete':
                                $this->attributesRepository->removeAttributeForUser($user->id, $key);
                                $deletedAttributes[] = $key;
                                break;
                            default:
                                // Unknown action
                                break;
                        }
                    }

                    // After handling the operations, send a confirmation to the assistant
                    $messages[] = [
                        'role' => 'function',
                        'name' => $functionName,
                        'content' => json_encode(['status' => 'success']),
                    ];

                    // Get the final response after function execution
                    $response = $client->chat()->create([
                        'model' => 'gpt-4',
                        'messages' => $messages,
                    ]);
                    $chatMessage = $response->choices[0]->message;
                }
            }

            // Return the assistant's reply along with attribute changes
            return response()->json([
                'message' => 'Chatbot response generated successfully.',
                'data' => [
                    'response' => $chatMessage->content,
                    'updated_attributes' => $updatedAttributes,
                    'deleted_attributes' => $deletedAttributes,
                ],
            ], 200);

        } catch (\Exception $e) {
            // Handle exceptions or API errors
            return response()->json([
                'message' => 'An error occurred while generating the response.',
                'error' => 'Internal server error.',
            ], 500);
        }
    }
}
