<?php
namespace App\Http\Controllers\Chat;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use OpenAI;
use App\Repositories\DynamicProfileAttributesRepository;
use Illuminate\Support\Facades\Validator;

/**
 * Handles chatbot interactions with OpenAI integration.
 */
class ChatController extends Controller
{
    protected DynamicProfileAttributesRepository $attributesRepository;

    /**
     * Inject the repository for dynamic profile attributes.
     */
    public function __construct(DynamicProfileAttributesRepository $attributesRepository)
    {
        $this->attributesRepository = $attributesRepository;
    }

    /**
     * Process user messages and generate chatbot responses.
     *
     * Accepts an array of messages and returns a response generated by OpenAI's GPT-4 model.
     * Manages user profile attributes dynamically based on the conversation.
     *
     * @group Chat
     * @authenticated
     *
     * @bodyParam messages array required An array of message objects with 'role' and 'content'.
     *
     * @response 200 {
     * "message": "Chatbot response generated successfully.",
     * "data": {
     * "response": "Hello! How can I assist you today?"
     * }
     * }
     *
     * @response 422 {
     * "message": "Validation failed.",
     * "errors": {
     * "messages": ["The messages field is required."]
     * }
     * }
     */
    public function interact(Request $request)
    {
        $user = $request->user();

        // Validate the request input
        $validator = Validator::make($request->all(), [
            'messages' => 'required|array',
            'messages.*.role' => 'required|string|in:user,assistant',
            'messages.*.content' => 'required|string',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'message' => 'Validation failed.',
                'errors' => $validator->errors(),
            ], 422);
        }

        // Retrieve user attributes to include in the context
        $userAttributes = $this->attributesRepository->getAttributesForUser($user->id)->toArray();

        // Prepare the system prompt with user attributes
        $systemPrompt = "User profile attributes: " . json_encode($userAttributes);

        // Prepend the system prompt to the messages
        $messages = array_merge([
            ['role' => 'system', 'content' => $systemPrompt],
        ], $request->messages);

        // Initialize the OpenAI client
        $openAiApiKey = config('services.openai.api_key');
        $client = OpenAI::client($openAiApiKey);

        try {
            // Call the OpenAI API with function definitions for attribute management
            $response = $client->chat()->create([
                'model' => 'gpt-4o',
                'messages' => $messages,
                'functions' => [
                    [
                        'name' => 'add_attribute',
                        'description' => 'Add a new attribute to the user profile',
                        'parameters' => [
                            'type' => 'object',
                            'properties' => [
                                'key' => [
                                    'type' => 'string',
                                    'description' => 'Attribute key to add',
                                ],
                                'value' => [
                                    'type' => 'string',
                                    'description' => 'Value of the attribute',
                                ],
                            ],
                            'required' => ['key', 'value'],
                        ],
                    ],
                    [
                        'name' => 'delete_attribute',
                        'description' => 'Delete an attribute from the user profile',
                        'parameters' => [
                            'type' => 'object',
                            'properties' => [
                                'key' => [
                                    'type' => 'string',
                                    'description' => 'Attribute key to delete',
                                ],
                            ],
                            'required' => ['key'],
                        ],
                    ],
                    [
                        'name' => 'update_attribute',
                        'description' => 'Update an existing attribute in the user profile',
                        'parameters' => [
                            'type' => 'object',
                            'properties' => [
                                'key' => [
                                    'type' => 'string',
                                    'description' => 'Attribute key to update',
                                ],
                                'value' => [
                                    'type' => 'string',
                                    'description' => 'New value of the attribute',
                                ],
                            ],
                            'required' => ['key', 'value'],
                        ],
                    ],
                ],
                'function_call' => 'auto',
            ]);

            $chatMessage = $response->choices[0]->message;

            // Handle function calls if any
            if (isset($chatMessage->functionCall)) {
                $functionName = $chatMessage->functionCall->name;
                $arguments = json_decode($chatMessage->functionCall->arguments, true);

                switch ($functionName) {
                    case 'add_attribute':
                        $this->attributesRepository->setAttributeForUser($user->id, $arguments['key'], $arguments['value']);
                        break;
                    case 'delete_attribute':
                        $this->attributesRepository->removeAttributeForUser($user->id, $arguments['key']);
                        break;
                    case 'update_attribute':
                        $this->attributesRepository->setAttributeForUser($user->id, $arguments['key'], $arguments['value']);
                        break;
                    default:
                        // Unknown function call
                        break;
                }

                // Recursive call to get the final response after function execution
                $messages[] = [
                    'role' => 'function',
                    'name' => $functionName,
                    'content' => json_encode(['status' => 'success']),
                ];

                $response = $client->chat()->create([
                    'model' => 'gpt-4o',
                    'messages' => $messages,
                ]);

                $chatMessage = $response->choices[0]->message;
            }

            // Return the assistant's reply
            return response()->json([
                'message' => 'Chatbot response generated successfully.',
                'data' => [
                    'response' => $chatMessage->content,
                ],
            ], 200);
        } catch (\Exception $e) {
            // Handle exceptions or API errors
            return response()->json([
                'message' => 'An error occurred while generating the response.',
                'error' => $e->getMessage(),
            ], 500);
        }
    }
}
